name: Deploy Node Application 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image 
        run: docker build -t gillnavi/nodejs-app .
      - name: Publish Image on docker hub
        run: docker push gillnavi/nodejs-app:latest 
        


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from the docker hub
        run: docker pull gillnavi/nodejs-app:latest
      - name: Run Docker Container
        run: docker run -d -p 3001:3001 --name --env-file /app  nodejs-app-container gillnavi/nodejs-app:latest 
